Ticket11 add queries toapi/reviews
FimbulWinters/NC-games pull request #9
Opened 2022-11-17 15:19 UTC by FimbulWinters

2022-11-17 15:24 UTC, pkaodev commented on Models/getModels.js
> +  ];
Split this into 2 allowed arrays - one for sort by, one for order

2022-11-17 15:28 UTC, pkaodev commented on Models/getModels.js
> +    }
What if the category exists but has no reviews (yet)?  Currently it would get a 404, but really it should be a 200 (it has successfully gotten the reviews, but there just happens to be none).

Instead of doing it like this, you can query earlier on to see if the category exists, and throw the error then.

(children's games is a category with no reviews)

2022-11-17 15:29 UTC, pkaodev commented on __tests__/get.test.js
> +          expect(result.body.reviews).toBeInstanceOf(Array);
don't need 70 - using forEach implies that it is an array

2022-11-17 15:30 UTC, pkaodev commented on __tests__/get.test.js
> +          expect(result.body.reviews).toBeInstanceOf(Array);
same with 93 as 70

2022-11-17 15:33 UTC, pkaodev commented on __tests__/get.test.js
> +        });
this test isn't checking if the array has been sorted by 'owner' in descending order (should be the default).

use something like:
https://www.npmjs.com/package/jest-sorted
to check if the array has been sorted as you expect it

2022-11-17 15:34 UTC, pkaodev commented on __tests__/get.test.js
> +          expect(result.body.reviews).toBeInstanceOf(Array);
same here, don't need to check if you're using array methods later on

2022-11-17 15:34 UTC, pkaodev commented on __tests__/get.test.js
> +        .get("/api/reviews?order=desc")
default will be desc, so we want to add another test for when order=asc

2022-11-17 15:35 UTC, pkaodev commented on __tests__/get.test.js
> +          });
use jest-sorted like explained previous comment

2022-11-17 15:36 UTC, pkaodev commented on __tests__/get.test.js
> +    describe("categories", () => {
categories?

2022-11-17 15:37 UTC, pkaodev commented on __tests__/get.test.js
> +      test("return 404 when category provided doesnt exist", () => {
this should be a 400

2022-11-17 15:38 UTC, pkaodev commented on __tests__/get.test.js
> +  });
add another test for 200: category exists but has no reviews in it (for children's games for example)

2022-11-17 15:38 UTC, pkaodev commented on db/seeds/utils.js
> +};
nice use of util function

2022-11-17 15:39 UTC, pkaodev commented
Please see comments, let me know if you want to discuss any of these.  Please put in another PR when you have done these.

2022-11-17 16:56 UTC, FimbulWinters commented on __tests__/get.test.js
> +        });
thanks for the note on jest-sorted. I haven't used it in this case, but i've made note of it for future!

2022-11-18 10:43 UTC, cjplatten reviewed
Please see comments

2022-11-18 10:43 UTC, cjplatten commented on __tests__/get.test.js
> +          .get("/api/reviews?order=desc")
if this is the default order you should test that it's in this order without the query.

2022-11-18 10:43 UTC, cjplatten commented on __tests__/get.test.js
> +            expect(result.body.reviews[0]).toMatchObject({
For this and the descending order test, you are only testing that the first entry on the returned array matches expectated obejct, you aren't testing that the rest of the array is in the correct order.

2022-11-18 11:31 UTC, callumu21 requested changes
Some changes required, and additional test cases to make sure that queries will work together rather than just individually.

2022-11-18 11:31 UTC, callumu21 commented on Controllers/getController.js
> +        res.send(reviews);
You would still return the empty array on a key of reviews here, so no need for the if/else logic

2022-11-18 11:31 UTC, callumu21 commented on Models/getModels.js
> +      if (sortBy) {
This logic is either/or and won't allow you to have a sort and order query at the same time. Try to join them together, and maybe use default values if one or the other isn't provided at all.

2022-11-18 11:31 UTC, callumu21 commented on Models/getModels.js
> +      console.log(queryString);
Console.log! 😱

2022-11-18 11:31 UTC, callumu21 commented on Models/getModels.js
> +          if (sortBy !== "default") {
You shouldn't allow default as an option. The default option of 'created_at' is when they don't provide a query at all.

2022-11-18 11:31 UTC, callumu21 commented on Models/getModels.js
> +exports.selectReviews = (categories, sortBy, order, query) => {
Look at setting parameters to default values when they aren't provided. It will make this much easier 👍

2022-11-18 11:31 UTC, callumu21 commented on __tests__/get.test.js
> +          .get("/api/reviews?sort_by=default")
The default value should be for when users don't provide a sort_by query. Here, 'default' should be an invalid sort_by query

2022-11-18 11:31 UTC, callumu21 commented on __tests__/get.test.js
> +            expect(result.body.reviews[0]).toMatchObject({
Ideally, jest-sorted should be used here, as you're just validating the first result, not all of them.

2022-11-18 11:31 UTC, callumu21 commented on __tests__/get.test.js
> +    });
You also need to test that sort_by and order work in tandem together (e.g. /api/reviews?sort_by=owner&order=asc)

2022-11-18 14:59 UTC, callumu21 approved these changes
Looks good, Alex! Just make sure to delete console.logs before pushing

2022-11-18 14:59 UTC, callumu21 commented on Models/getModels.js
> +      console.log(queryString);
This is still in here!

2022-11-18 15:02 UTC, merged